# Generated by Django 3.1.2 on 2020-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year_in_school',
            field=models.CharField(choices=[('SOFIA', 'Sofia')], default='SOFIA', max_length=10),
        ),
    ]
