# Generated by Django 3.1.2 on 2020-10-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='year_in_school',
            new_name='main_city',
        ),
    ]
