# Generated by Django 3.1.2 on 2020-10-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201003_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_city',
            field=models.CharField(choices=[('SOFIA', 'Sofia'), ('BURGAS', 'Burgas'), ('PLOVDIV', 'Plovdiv'), ('VARNA', 'Varna'), ('RUSE', 'Ruse')], default='SOFIA', max_length=10),
        ),
    ]
